### ISSUE TITLE
Consider registering CIT context mapping to CBOR-LD registry

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalbazaar/bedrock-tokenization#29]
Consider registering the Concealed Id Token CBOR-LD context mapping (`0x8000 -> 'https://w3id.org/cit/v1.jsonld'` currently) in the CBOR-LD registry (currently over at the [cbor-ld ContextCodec](https://github.com/digitalbazaar/cborld/blob/main/lib/codecs/ContextCodec.js#L9)).

**Comment by dlongley** [comment]
Already done here: https://github.com/digitalbazaar/cborld/blob/main/lib/codecs/registeredContexts.js#L16
